name = "dondone-auth"
compatibility_date = "2026-06-10"
compatibility_flags = ["global_fetch_strictly_public"]
pages_build_output_dir = "dist"

[vars]
SUPABASE_URL = "https://ttmrvhkmqljulrptviow.supabase.co"
SUPABASE_PUBLISHABLE_KEY = "sb_publishable_5jnBwB84hcwhi2uwqPJQpQ_VBP161NF"
DONDONE_JWT_KID = "dondone-auth-es256-1"
DONDONE_JWT_ISSUER = "https://auth.dondone.dev"
ADMIN_ALLOWED_ORIGINS = "https://console.dondone.dev"

[[kv_namespaces]]
binding = "AUTH_CODES" # simple-auth-codes
id = "5e97806b185044c99c982330b88aba61"
